### ISSUE TITLE
Save function

### ISSUE THREAD

**Issue by chrisharrison** [Sybio/GifFrameExtractor#1]
Any chance this class can have a way to save the manipulated frames back out into an animated GIF again?

**Comment by Sybio** [comment]
You should used https://github.com/Sybio/GifCreator that I create to perform this ^^

I invite you to read this short tutorial, it used GifFrameExtractor and GifCreator (and also a third class ImageWorkshop to resize and watermark) -> http://phpimageworkshop.com/tutorial/5/manage-animated-gif-with-imageworkshop.html
