### ISSUE TITLE
Frame Durations

### ISSUE THREAD

**Issue by logger24** [Sybio/GifFrameExtractor#2]
It seems that the frame durations are missing a place.
When I get the frame duration of a 10000ms frame, it returns only 1000.
When I get the frame duration of a 200ms frame, it returns only 20.
Unless I'm mistaken.

**Comment by yang-jandro** [comment]
@logger24 GIF file format implementation measures time frames in hundredths of a second.

Nice read here:
http://www.matthewflickinger.com/lab/whatsinagif/animation_and_transparency.asp

**Comment by logger24** [comment]
So it's returning centiseconds. Frustration caused by animation suites letting you handle timing in a plethora of ways. Don't much miss GIFs with countless better and standardized stuff out now, though, so closed.

**Comment by logger24** [comment]
Lastly, thanks for clearing it up and showing me their structure. Nice to RTFM so I could work with it.
