### ISSUE TITLE
Add method to fetch the number of times a gif loops.

### ISSUE THREAD

**Issue by hellopablo** [Sybio/GifFrameExtractor#3]
Can I request that a method be added which tells you the number of times a gif loops? I'm extracting frames then resizing them and then using your other library (GifCreator) to recompile the frames back into an animated gif.

For the moment I'm setting it to loop indefinitely, but ideally I should specify the number of loops as specified in the source file.

_If there's a simple vanilla PHP way of getting the loops then I'm all ears!_

**Comment by betzholz** [comment]
Hey Yeah just get it :)
Am 27.09.2013 um 15:59 schrieb Pablo de la Peña notifications@github.com:

**Comment by hellopablo** [comment]
... how? I can't see any reference to the number of loops anywhere in the source?

**Comment by betzholz** [comment]
Hey Sorry i didn't get ur request right...
As now there ist no option to read  how many loops the original gif have but will work on it...

Greetz :)
Am 27.09.2013 um 16:20 schrieb Pablo de la Peña notifications@github.com:

**Comment by yang-jandro** [comment]
If anyone is interested, I added the ability to get number of loops in current open pull request.

**Comment by hellopablo** [comment]
Thanks @gpv-dev, your patch works well, thanks! @Sybio, can we see this merged into the main repo, s'il vous plaît?

**Comment by hellopablo** [comment]
Closing abandoned issues / clearing my issues inbox.
